### ISSUE TITLE
Problems in java files

### ISSUE THREAD

**Issue by ahmedaa6122** [felipeucelli/JavaTube#2]
When import java tube files in my project its show me this error in classes 

`/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/java/com/purplerat/myapplication/javatube/Captions.java:105: error: cannot find symbol
        Files.writeString(path, xmlCaptionToSrt(), StandardCharsets.UTF_8);
             ^
  symbol:   method writeString(Path,String,Charset)
  location: class Files
/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/java/com/purplerat/myapplication/javatube/Captions.java:111: error: cannot find symbol
        Files.writeString(path, getXmlCaptions(), StandardCharsets.UTF_8);
             ^
  symbol:   method writeString(Path,String,Charset)
  location: class Files
/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/java/com/purplerat/myapplication/javatube/Playlist.java:114: error: cannot find symbol
        if (!continuationEnd.isEmpty()) {
                            ^
  symbol:   method isEmpty()
  location: variable continuationEnd of type JSONArray
/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/java/com/purplerat/myapplication/javatube/Channel.java:108: error: cannot find symbol
                if (!continuationEnd.isEmpty()){
                                    ^
  symbol:   method isEmpty()
  location: variable continuationEnd of type JSONArray
/storage/emulated/0/AndroidIDEProjects/MyApplication/app/src/main/java/com/purplerat/myapplication/javatube/Search.java:20: error: incompatible types: Charset cannot be converted to String
        return URLEncoder.encode(this.query, StandardCharsets.UTF_8);`

How solve this ?

**Comment by felipeucelli** [comment]
**Machine translated**

Make sure you are using the latest JavaTube update as of the date of the issue

Provide YouTube URL, playable JavaTube code and expected behavior
