### ISSUE TITLE
How use it 

### ISSUE THREAD

**Issue by ahmedaa6122** [felipeucelli/JavaTube#3]
I need to know how use this library in my android studio project?

**Comment by felipeucelli** [comment]
### Configure the project
1. You need to configure gradle for java version 11 or higher.

2. Add dependencies `'io.apisense:rhino-android:1.0'` (used to handle youtube javascript) and in some cases you also need to add **org.json** library.

3. copy folder [javatube](https://github.com/felipeucelli/JavaTube/tree/master/src/main/java) into **/app/src/main/java/** of your project, or you can compile the java files to **.jar** and copy it to your project's **/app/libs/** folder and configure the dependency in gradle: `implementation files('libs/JavaTube.jar')`.

4. If everything went well with importing the code and dependencies, you can now import javatube into your code, for example: `import javatube.Youtube;`.


### The useful classes are
- **Youtube** (obtaining more complete information about the videos), 
- **Playlist** (obtaining playlist information), 
- **Channel** (obtaining channel information),
- **Search** (allows you to perform searches by keywords and return videos, YouTube shorts, channels and playlists related to your search).


### Code example
This code will create a new **Youtube** object, it will access the video streams and will download the highest quality progressive stream (audio and video in a single file) to the path **"./"**:
- `new Youtube("https://www.youtube.com/watch?v=60ItHLz5WEA").streams().getHighestResolution().download("./");`.

**Comment by ahmedaa6122** [comment]
Thanks sir but please upload it to jitpack in the future 👍❤
