### ISSUE TITLE
The searching is taking a very long time

### ISSUE THREAD

**Issue by roeinissim** [felipeucelli/JavaTube#4]
Hey, I really like your code and it so much fun to work with it and really everything is working fine, but the searching is taking a very long time something like 10 - 15 seconds, can I improve it somehow?

**Comment by felipeucelli** [comment]
Hi @roeinissim In my tests it is working normally. But feel free to make improvements, I'm happy to receive suggestions.

**Comment by roeinissim** [comment]
Understood, thank you!
