### ISSUE TITLE
Regex Matcher Exception

### ISSUE THREAD

**Issue by roeinissim** [felipeucelli/JavaTube#5]
Hey, when I use the 'stream()' function is gives me the error: "Fsa=function\(\w\)\{[a-z]=[a-z]\.[a-z]*\(\"\"\);([\w*\.\w*\(\w,\d\);]*)(?:return)", how can I fix it?

**Comment by felipeucelli** [comment]
Sometimes YouTube updates its **base.js** and breaks some things. The fix is ​​now available [here](https://github.com/felipeucelli/JavaTube/commit/a50f6497627a6d4477daa978d229382ecce79760). Thanks for reporting.

**Comment by roeinissim** [comment]
Working perfectly now!
Thank you
