### ISSUE TITLE
issue with the adaptive videos

### ISSUE THREAD

**Issue by roeinissim** [felipeucelli/JavaTube#8]
Hey, for some reason I can not load the adaptive videos that are in the streamQuery given in the stream() method in Youtube class, can it be fixed somehow?

**Comment by felipeucelli** [comment]
Hi @roeinissim, please provide me JavaTube code and output.

**Comment by roeinissim** [comment]
I can't reach my computer right now but I can tell you that I tried with a few videos so far and in each try it gave me a lot of adaptive streams and 1 progressive stream in the stream query, the progressive stream is working fine but it is always in a resolution of 360p, the adaptive streams are taking a lot of time to load in the media player and then after like 1 minute of loading it is only video without sound.

**Comment by felipeucelli** [comment]
YouTube uses a streaming technique called Dynamic Adaptive Streaming over HTTP (DASH), this implies how streams are provided, in this case, progressive streams provide audio and video in a single file (usually in resolution between 360p and 720p) , while adaptive provides the audio and video in separate files (usually at higher qualities). Adaptive streams are generally larger in quantity than progressive streams, but the audio and video are separate.

To have higher quality videos, you can download the video and then the audio and merge it using **ffmpeg** for example.

The **WEB** client that JavaTube currently uses only provides a progressive stream.

**ANDROID** clients usually offer progressive streams in 360p and 720p resolution, however they can generate various types of errors in certain videos.

To change the client, change the function in **Youtube.java**:

```java
    private JSONObject getVidInfo() throws Exception {
        if(vidInfo == null){
            vidInfo = setVidInfo();
        }
        return vidInfo;
    }
```
For

```java
    private JSONObject getVidInfo() throws Exception {
        if(vidInfo == null){
            vidInfo = new InnerTube("ANDROID_MUSIC").player(videoId());
        }
        return vidInfo;
    }
```
You can check available clients at **InnerTube.java**


**Extra Info**: For some reason YouTube provides adaptive streams called OTF for some videos, which need to be downloaded in sequential chunks.

**Comment by roeinissim** [comment]
thank you very much for the large explanation!
